version: "3.4"
services:
  database:
    env_file: .env
    image: postgres:16.2
    volumes:
      - ./backend/src/common/database/schemas:/docker-entrypoint-initdb.d
      - ./.docker/postgres/data:/var/lib/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"